platform :ios, "7.1"

target "JVEReactiveItemDownloader" do
	pod 'ReactiveCocoa'
	pod 'ReactiveViewModel'
end

target "JVEReactiveItemDownloaderTests" do
    pod 'ReactiveCocoa'
	pod 'ReactiveViewModel'
end

