platform :ios, "7.1"

target "JVEReactiveItemDownloader" do
	pod 'ReactiveCocoa'
	pod 'ReactiveViewModel'
    pod 'libextobjc'
    pod 'JVRCellConfiguratorDelegate'
end

target "JVEReactiveItemDownloaderTests" do
end

